//! Generated by `rustlavel make:migration`. Do not edit.
//!
//! A compiled program cannot discover migrations by scanning a directory, so
//! the CLI keeps this list in step with the files beside it.

pub mod m2026_08_29_090821_create_posts_table;
use rustlavel::db::Migration;

/// Every migration, in the order they must run.
pub fn all() -> Vec<&'static dyn Migration> {
    vec![
        &m2026_08_29_090821_create_posts_table::CreatePostsTable,
    ]
}
