//! Generated by the rustlavel CLI. Do not edit.
//!
//! The authorization server's tables, and only its. The resource server has a
//! database of its own and never reads these.

#[path = "2026_09_06_000100_create_oauth_tables.rs"]
mod create_oauth_tables;

pub fn all() -> Vec<&'static dyn rustlavel::db::Migration> {
    vec![&create_oauth_tables::CreateOauthTables]
}
