//! Generated by the rustlavel CLI. Do not edit.

#[path = "first_client_seeder.rs"]
mod first_client_seeder;

pub fn all() -> Vec<&'static dyn rustlavel::db::Seeder> {
    vec![&first_client_seeder::FirstClientSeeder]
}
