[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Advance Dynamic Software"]
repository = "https://github.com/advancedynamic/rustlavel"

[workspace.dependencies]
rustlavel-core = { path = "crates/rustlavel-core", version = "0.1.0" }
rustlavel-http = { path = "crates/rustlavel-http", version = "0.1.0" }
rustlavel-auth = { path = "crates/rustlavel-auth", version = "0.1.0" }
rustlavel-i18n = { path = "crates/rustlavel-i18n", version = "0.1.0" }
rustlavel-client = { path = "crates/rustlavel-client", version = "0.1.0" }
rustlavel-cache = { path = "crates/rustlavel-cache", version = "0.1.0" }
rustlavel-db = { path = "crates/rustlavel-db", version = "0.1.0" }
rustlavel-macros = { path = "crates/rustlavel-macros", version = "0.1.0" }
rustlavel-view = { path = "crates/rustlavel-view", version = "0.1.0" }
rustlavel-storage = { path = "crates/rustlavel-storage", version = "0.1.0" }
rustlavel-validation = { path = "crates/rustlavel-validation", version = "0.1.0" }
rustlavel-telescope = { path = "crates/rustlavel-telescope", version = "0.1.0" }
rustlavel-ai = { path = "crates/rustlavel-ai", version = "0.1.0" }
rustlavel-queue = { path = "crates/rustlavel-queue", version = "0.1.0" }
rustlavel-mail = { path = "crates/rustlavel-mail", version = "0.1.0" }
tokio = { version = "1", features = ["full"] }
