[package]
name = "rustlavel-view"
description = "Rustlavel templating: Blade-inspired layouts, sections, and automatic escaping"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = "README.md"
authors.workspace = true
repository.workspace = true

[dependencies]
rustlavel-core.workspace = true
