//! Generated by the rustlavel CLI. Do not edit.
//!
//! The resource server's tables, and only its. The authorization server has a
//! database of its own and never reads these.

#[path = "2026_09_16_000100_create_orders_table.rs"]
mod create_orders_table;

pub fn all() -> Vec<&'static dyn rustlavel::db::Migration> {
    vec![&create_orders_table::CreateOrdersTable]
}
